[[articles]]
title = 'In which I write a thing.'
author = 'Dave'
date = 2022-09-15
content = '''
This is a placeholder article whilst I work out the layout and think of something worth writing about.
'''
