name: ci
on: push
jobs:
  build-html:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir dist
      - run: |
          yarn install
          yarn exec -- static-site-generator --outFile dist/index.html
      - uses: actions/upload-artifact@v3
        with:
          name: built
          path: dist
  build-style:
    name: Build Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir dist
      - run: cp static/style.css dist
      - uses: actions/upload-artifact@v3
        with:
          name: built
          path: dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
    needs:
      - build-html
      - build-style
    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ${{ secrets.DEPLOY_REGION }}
      - uses: actions/download-artifact@v3
        with:
          name: built
          path: dist
      - run: aws s3 sync dist/ s3://${{ secrets.DEPLOY_BUCKET }}
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEPLOY_DISTRIBUTION }} --paths '/*'
