name: ci
on: push
jobs:
  build-html:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: "20.x"
      - run: mkdir -p dist/article
      - run: |
          yarn install
          yarn exec -- static-site-generator --outDir dist/article --outFile dist/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: html
          path: dist
  build-style:
    name: Build Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: mkdir dist
      - run: cp static/style.css dist
      - uses: actions/upload-artifact@v4
        with:
          name: style
          path: dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
    needs:
      - build-html
      - build-style
    steps:
      - uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ${{ secrets.DEPLOY_REGION }}
      - uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true
        # Remove the html extensions to get nice permalinks for now.
      - run: find dist/article -type f -name '*.html' -exec sh -c 'for file do mv "$file" "${file%.html}"; done' sh {} +
      - run: aws s3 sync dist/ s3://${{ secrets.DEPLOY_BUCKET }} --include '*' --exclude 'article/*'
      - run: aws s3 sync dist/ s3://${{ secrets.DEPLOY_BUCKET }} --include 'article/*' --content-type 'text/html'
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEPLOY_DISTRIBUTION }} --paths '/*'
